get:
	curl -X GET 'https://signal.unexpectedeof.casa/?service=ON_AIR&psk='

publish:
	wrangler publish

preview:
	wrangler preview --watch

update:
	curl -X POST 'https://signal.unexpectedeof.casa/?service=ON_AIR&status=<>&psk=<>'

