name = "signal"
type = "javascript"
account_id = "71d34bfddb24398d3316987ca0abe9df"
route = "https://signal.unexpectedeof.casa/*"
zone_id = "c4bf237d62f19e697f634cf753867c2d"

kv-namespaces = [
	{binding = "SIGNALS", id = "fe9c6b21f5604710a8093a00c775adaf"}
]
